language: node_js
python: stable
node_js: stable

notifications:
  email:
    recipients:
      - 674964222@qq.com
    on_success: change # default: change
    on_failure: always # default: always

install:
  - npm install
 
script:
  - hexo clean
  - git rev-parse HEAD > VERSION.txt

after_script:
  - echo 'Build Master Repository(Coding Pages)'
  - hexo generate
  #- cp albums.json ./public/albums.json
  - git config user.name "gating"
  - git config user.email "674964222@qq.com"
  - cd ./public
  - git init
  - git remote add origin master https://github.com/gating/gating.github.io 
  - git add .
  - git commit -m "Coding Pages Build"
  - git push --force --quiet "https://${CO_USER}:${CO_TOKEN}@${CO_REF}" master:master
  # Prepare Rebuild
  - cd ..
  - rm -rf ./public
  - hexo clean
  - echo 'Build Salver Repository(Github Pages)'
  - hexo generate
  - git config user.name "gating"
  - git config user.email "674964222@qq.com"
  - cd ./public
  - git init 
  - git remote add origin master https://github.com/gating/qinyuanpe.github.io
  - git add .
  - git commit -m "Github Pages Build"
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master --tags

addons:
  apt:
    update: true

branches:
  only:
    - master

env:
 global:
   # Github Pages
   - GH_REF: github.com/GATING/gating.github.io.git
   # Coding Pages
   - CO_REF: e.coding.net/gating/family.git