language: node_js
python: stable
node_js: stable

notifications:
  email:
    recipients:
      - 674964222@qq.com
    on_success: change # default: change
    on_failure: always # default: always

before_install:
  - export TZ='Asia/Shanghai'
  - npm install hexo-cli -g

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo generate


after_script:
  - git config user.name "gating"
  - git config user.email "674964222@qq.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml && sed -i "s/co_token/${CO_TOKEN}/g" ./_config.yml
  - hexo algolia && hexo deploy

addons:
  apt:
    update: true

branches:
  only:
    - blog

env:
 global:
   # Github Pages
   - GH_REF: github.com/GATING/gating.github.io.git
   # Coding Pages
   - CO_REF: e.coding.net/gating/family.git