language: node_js
python: stable
node_js: stable

notifications:
  email:
    recipients:
      - 674964222@qq.com
    on_success: change # default: change
    on_failure: always # default: always


before_install:
- npm install hexo-cli -g

install:
  - npm install
 
script:
  - hexo clean
  - hexo generate


after_script:
  - cd ./public
  - git init 
  - git config user.name "gating"
  - git config user.email "674964222@qq.com"
  - git add .
  - git commit -m "Pages Build"
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master
  - git push --force --quiet "https://gating:${CO_TOKEN}@${CO_REF}" master:master

addons:
  apt:
    update: true

branches:
  only:
    - master

env:
 global:
   # Github Pages
   - GH_REF: github.com/GATING/gating.github.io.git
   # Coding Pages
   - CO_REF: e.coding.net/gating/family.git